#!/usr/bin/env bash

directories=(~/repo ~/.ssh)

for dir in "${directories[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

cur_dir=$(pwd)
repo_dir=~/repo
cd "$repo_dir" || exit

git clone https://github.com/whonathan/topsecret.git &>/dev/null
cd topsecret || exit

echo -n "Enter passphrase: "
read -s PASSPHRASE
echo

enc_files=(
    ".ssh/id_ed25519.enc"
    ".ssh/id_ed25519.pub.enc"
    ".ssh/known_hosts.enc"
    ".ssh/known_hosts.old.enc"
    ".gitconfig.enc"
)

for FILE in "${enc_files[@]}"; do
    openssl enc -aes-256-cbc -d -pbkdf2 -pass pass:"$PASSPHRASE" -in "$FILE" -out ${FILE%.enc}
    if [ $? -ne 0 ]; then
        exit 1
    fi
done

paths=(
    ".ssh/id_ed25519"
    ".ssh/id_ed25519.pub"
    ".ssh/known_hosts"
    ".ssh/known_hosts.old"
    ".gitconfig"
)

for path in "${paths[@]}"; do
    full_path=~/"$path"
    if [ -e "$full_path" ]; then
        if [ -d "$full_path" ]; then
            rm -fr "$full_path"
        elif [ -f "$full_path" ]; then
            rm -f "$full_path"
        fi
    fi
    chmod 600 "$path"
    ln -fs "$repo_dir"/topsecret/"$path" "$full_path"
done

git remote set-url origin git@github.com:whonathan/topsecret.git

cd "$cur_dir"
