#!/usr/bin/env bash

directories=(~/repo)

for dir in "${directories[@]}"; do
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
done

repo_dir=~/repo
cd "$repo_dir" || exit

git clone https://github.com/whonathan/topsecret.git

paths=(
    ".ssh"
    ".gitconfig"
)

for path in "${paths[@]}"; do
    full_path=~/"$path"
    if [ -e "$full_path" ]; then
        if [ -d "$full_path" ]; then
            rm -fr "$full_path"
        elif [ -f "$full_path" ]; then
            rm -f "$full_path"
        fi
    fi
    ln -fs "$repo_dir"/topsecret/"$path" "$full_path"
done
